
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: health-monitor
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'YOUR_GIT_REPOSITORY_URL'
    path: k8s-manifests/base
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
